import os

os.environ['SECRETY_KEY']="open sessame"
os.environ['SQL_SERVER']="jkas-server.database.windows.net"
os.environ['SQL_PORT']="1433"
os.environ['SQL_DATABASE']="jkasdb"
os.environ['SQL_UID']="jkasadmin"
os.environ['SQL_PASSWORD']="P@ssw0rd"
os.environ['SMTP_MAIL']="jkas.ppks@gmail.com"
os.environ['SMTP_PASSWORD']="Jkas@123"
os.environ['FROM_EMAIL']="evangrace98@gmail.com"
os.environ['SEND_GRID_KEY']="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"
os.environ['PRIVATE_PHOTO_FOLDER']="/Users/faizal/JKAS_FILES/images//"
os.environ['PRIVATE_DOC_FOLDER']="/Users/faizal/JKAS_FILES/pdfs/"
os.environ['PUBLIC_PHOTO_FOLDER']="/Users/faizal/JKAS_FILES/freeimages/"
os.environ['PUBLIC_DOC_FOLDER']="/Users/faizal/JKAS_FILES/freepdfs/"
os.environ['PUBLIC_VIDEO_FOLDER']="/Users/faizal/JKAS_FILES/videos/"
os.environ['UI_URL']="http://localhost:4200"
os.environ['DOC_FOLDER']="./assets/"
