import os

os.environ['SECRETY_KEY']="open sessame"
os.environ['SQL_SERVER']="mysuites.southeastasia.cloudapp.azure.com"
os.environ['SQL_PORT']="1433"
os.environ['SQL_DATABASE']="JKAS"
os.environ['SQL_UID']="dbkljkas"
os.environ['SQL_PASSWORD']="iwaste123dbkl"
os.environ['SMTP_MAIL']="jkas.ppks@gmail.com"
os.environ['SMTP_PASSWORD']="Jkas@123"
os.environ['FROM_EMAIL']="jkas.ppks@gmail.com"
os.environ['PRIVATE_PHOTO_FOLDER']="/Users/faizal/JKAS_FILES/images//"
os.environ['PRIVATE_DOC_FOLDER']="/Users/faizal/JKAS_FILES/pdfs/"
os.environ['PUBLIC_PHOTO_FOLDER']="/Users/faizal/JKAS_FILES/freeimages/"
os.environ['PUBLIC_DOC_FOLDER']="/Users/faizal/JKAS_FILES/freepdfs/"
os.environ['PUBLIC_VIDEO_FOLDER']="/Users/faizal/JKAS_FILES/videos/"
os.environ['UI_URL']="https://ppks.ml"
os.environ['DOC_FOLDER']="./assets/"
